baseURL: https://joyyyshi.netlify.app/ 
languageCode: en-us
title: Portfolio website for Joy Shi
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Get Started
    subtitle: |-
      Bachelor of Business Administration @ RUC, Masters
      in Analytics and Management @ LBS
    title: Hi, welcome to website of Yuqiao(Joy) Shi.
  blog: {}
  contact:
    address:
      - city: London
        country: UK
        street: Regent's Park
        title: London Business School
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: yshi.mam2023@london.edu
        title: Email
    enable: yes
    phone:
      - phone: (0) 7474-896889
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: Joy
    enable: yes
    quicklinks:
    social:
      - icon: fa-twitter
        label: Twitter
        url: https://twitter.com/JoyyyShi0809
#      - icon: fa-facebook
#        label: Facebook
#        url: https://www.facebook.com
#      - icon: fa-instagram
#        label: Instagram
#        url: https://www.instagram.com
      - icon: fa-github
        label: GitHub
        url: https://github.com/JoyyyShi
      - icon: fa-linkedin
        label: LinkedIn
        url: https://www.linkedin.cn/incareer/in/yuqiao-shi-52639a20a
  image: ''
  name: Joy Shi
  navigation:
    button1:
      - name: About me
        url: Self-introduction
    button2:
      - name: Projects
        url: blogs
    links:
      - name: Home
        url: '#'
      - name: Projects
        url: blogs
      - name: CV
        url: CV_Yuqiao Shi.pdf
      - name: About me
        url: Self-introduction
    menu: Menu
    title: Joy Shi
  tiles:
    enable: yes
    showcase:
      - image: pic01.jpg
        subtitle: Do you want to know more about my life?
        title: About me
        url: Self-introduction
      - image: pic02.jpg
        subtitle: Looking for chances in investment banking.
        title: My CV
        url: CV_Yuqiao Shi.pdf
#      - image: pic03.jpg
#        subtitle: Looking for chances in investment banking.
#        title: My CV
#        url: CV_Yuqiao Shi.pdf
#      - image: pic04.jpg
#        subtitle: My project
#        title: Analysis of IMDB Movies
#        url: IMDB Analysis
      - image: pic04.jpg
        subtitle: Click to see what I am doing recently.
        title: Recent things
        url: Recent
#      - image: pic06.jpg
#        subtitle: Feugiat Amet Tempus
#        title: Etiam
#        url: blogs/ipsum
  two:
    buttonText: My Projects
    enable: yes
    subtitle: Click to see my group projects about IMDB Analysis, Climate Changes,
    and more.
    title: Know More
    url: blogs
