---
categories:  
- ""    #the front matter should be like the one found in, e.g., blog2.md. It cannot be like the normal Rmd we used
- ""
date: "2022-09-20"
description: Climate change and temperature anomalies  # the title that will show up once someone gets to this page
draft: false
image: climate.jpg # save picture in \static\img\blogs. Acceptable formats= jpg, jpeg, or png . Your iPhone pics wont work
keywords: ""
slug: Climate # slug is the shorthand URL address... no spaces plz
title: Climate change and temperature anomalies
---



<div id="climate-change-and-temperature-anomalies" class="section level1">
<h1>Climate change and temperature anomalies</h1>
<pre><code>## Rows: 143 Columns: 19
## ── Column specification ────────────────────────────────────────────────────────
## Delimiter: &quot;,&quot;
## dbl (19): Year, Jan, Feb, Mar, Apr, May, Jun, Jul, Aug, Sep, Oct, Nov, Dec, ...
## 
## ℹ Use `spec()` to retrieve the full column specification for this data.
## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.</code></pre>
<p>I select the year and the twelve month variables from the
<code>weather</code>dataset. And then convert the dataframe from wide to ‘long’
format.</p>
<pre class="r"><code>tidyweather &lt;- weather %&gt;% 
  # Drop columns that are not needed
  select(Year:Dec) %&gt;% 
  # Pivot into longer format with columns 2:13 that contain the monthly data
  pivot_longer(cols = 2:13, 
               names_to = &quot;Month&quot;, 
               values_to = &quot;delta&quot;)</code></pre>
<div id="plotting-information" class="section level2">
<h2>Plotting Information</h2>
<p>Let us plot the data using a time-series scatter plot, and add a
trendline.</p>
<pre class="r"><code>tidyweather &lt;- tidyweather %&gt;%
  # use ymd function from lubridate package to create a date variable
  mutate(date = ymd(paste(as.character(Year), Month, &quot;1&quot;)),
         # Create month and year variable in the lubridate package
         month = month(date, label=TRUE),
         year = year(date))

# Create plot with smoothing line
ggplot(tidyweather, aes(x=date, y = delta))+
  geom_point()+
  geom_smooth(color=&quot;red&quot;) +
  theme_bw() +
  labs (
    title = &quot;Monthly Weather Anomalies&quot;
  )</code></pre>
<pre><code>## `geom_smooth()` using method = &#39;gam&#39; and formula &#39;y ~ s(x, bs = &quot;cs&quot;)&#39;</code></pre>
<pre><code>## Warning: Removed 4 rows containing non-finite values (stat_smooth).</code></pre>
<pre><code>## Warning: Removed 4 rows containing missing values (geom_point).</code></pre>
<p><img src="/blogs/climate_files/figure-html/scatter_plot-1.png" width="672" /></p>
<p>Is the effect of increasing temperature more pronounced in some months?
Use <code>facet_wrap()</code> to produce a separate scatter plot for each month,
again with a smoothing line. Your chart should human-readable labels;
that is, each month should be labeled “Jan”, “Feb”, “Mar” (full or
abbreviated month names are fine), not <code>1</code>, <code>2</code>, <code>3</code>.</p>
<pre class="r"><code># Create plot
ggplot(tidyweather, aes(x = date, y = delta, color = month))+
  geom_point() +
  geom_smooth(color=&quot;red&quot;) +
  theme_bw() +
  labs (
    title = &quot;Weather Anomalies by month&quot;) + 
  # One plot per month
  facet_wrap(~month)</code></pre>
<pre><code>## `geom_smooth()` using method = &#39;loess&#39; and formula &#39;y ~ x&#39;</code></pre>
<pre><code>## Warning: Removed 4 rows containing non-finite values (stat_smooth).</code></pre>
<pre><code>## Warning: Removed 4 rows containing missing values (geom_point).</code></pre>
<p><img src="/blogs/climate_files/figure-html/facet_wrap-1.png" width="672" /></p>
<p>It is sometimes useful to group data into different time periods to
study historical data. For example, we often refer to decades such as
1970s, 1980s, 1990s etc. to refer to a period of time. NASA calculates a
temperature anomaly, as difference form the base period of 1951-1980.
The code below creates a new data frame called <code>comparison</code> that groups
data in five time periods: 1881-1920, 1921-1950, 1951-1980, 1981-2010
and 2011-present.</p>
<p>We remove data before 1800 and before using <code>filter</code>. Then, we use the
<code>mutate</code> function to create a new variable <code>interval</code> which contains
information on which period each observation belongs to. We can assign
the different periods using <code>case_when()</code>.</p>
<pre class="r"><code>comparison &lt;- tidyweather %&gt;% 
  filter(Year&gt;= 1881) %&gt;%     # remove years prior to 1881
  #create new variable &#39;interval&#39;, and assign values based on criteria below:
  mutate(interval = case_when(
    Year %in% c(1881:1920) ~ &quot;1881-1920&quot;,
    Year %in% c(1921:1950) ~ &quot;1921-1950&quot;,
    Year %in% c(1951:1980) ~ &quot;1951-1980&quot;,
    Year %in% c(1981:2010) ~ &quot;1981-2010&quot;,
    TRUE ~ &quot;2011-present&quot;
  ))</code></pre>
<p>Inspect the <code>comparison</code> dataframe by clicking on it in the
<code>Environment</code> pane.</p>
<p>Now that we have the <code>interval</code> variable, we can create a density plot
to study the distribution of monthly deviations (<code>delta</code>), grouped by
the different time periods we are interested in. Set <code>fill</code> to
<code>interval</code> to group and colour the data by different time periods.</p>
<pre class="r"><code>ggplot(comparison, aes(x = delta, fill = interval)) + 
  geom_density() +
  labs (
    title = &quot;Density plot for monthly deviations&quot;
  )</code></pre>
<pre><code>## Warning: Removed 4 rows containing non-finite values (stat_density).</code></pre>
<p><img src="/blogs/climate_files/figure-html/density_plot-1.png" width="672" /></p>
<p>So far, we have been working with monthly anomalies. However, we might
be interested in average annual anomalies. We can do this by using
<code>group_by()</code> and <code>summarise()</code>, followed by a scatter plot to display
the result.</p>
<pre class="r"><code>#creating yearly averages
average_annual_anomaly &lt;- tidyweather %&gt;% 
  group_by(Year) %&gt;%   #grouping data by Year
  
  # use `na.rm=TRUE` to eliminate NA (not available) values 
  summarise(avg_anomalies = mean(delta, na.rm = TRUE)) 

#plotting the data:
ggplot(average_annual_anomaly, aes(x = Year, y = avg_anomalies)) + 
  geom_point() + 
  # Fitting the best line using LOESS method
  geom_smooth(color = &quot;red&quot;, method = &quot;loess&quot;) + 
  # Set theme to have white background with black frame
  theme_bw() + 
  labs(title = &quot;Average annual anomalies&quot;, y = &quot;Average anomaly&quot;)</code></pre>
<pre><code>## `geom_smooth()` using formula &#39;y ~ x&#39;</code></pre>
<p><img src="/blogs/climate_files/figure-html/averaging-1.png" width="672" /></p>
</div>
<div id="confidence-interval-for-delta" class="section level2">
<h2>Confidence Interval for <code>delta</code></h2>
<p><a href="https://earthobservatory.nasa.gov/world-of-change/decadaltemp.php">NASA points out on their
website</a>
that</p>
<blockquote>
<p>A one-degree global change is significant because it takes a vast
amount of heat to warm all the oceans, atmosphere, and land by that
much. In the past, a one- to two-degree drop was all it took to plunge
the Earth into the Little Ice Age.</p>
</blockquote>
<p>Let’s construct a confidence interval for the average delta since 2011,
both using a formula and using a bootstrap simulation with the <code>infer</code>
package.</p>
<pre class="r"><code>formula_ci &lt;- comparison %&gt;% 
  filter(interval == &quot;2011-present&quot;) %&gt;% 
  # drop na values to remove 2022 values that are in the future and are not yet available
  drop_na() %&gt;% 
  # Calculate avg, standard deviation and count from the data points
  summarise(avg = mean(delta, na.rm = TRUE), 
          sd = sd(delta), 
          count = n(), 
          # Calculate standard error based on standard deviation and count
          se = sd / sqrt(count), 
          # Use t distribution because population standard deviation is not known
          # Use 0.975 to have tails for 2.5% of values on both sides --&gt; results in 95% confidence interval 
          t_critical = qt(0.975, count-1), 
          lower_boundary = avg - se * t_critical, 
          upper_boundary = avg + se * t_critical) 

#print out formula_CI
formula_ci</code></pre>
<pre><code>## # A tibble: 1 × 7
##     avg    sd count     se t_critical lower_boundary upper_boundary
##   &lt;dbl&gt; &lt;dbl&gt; &lt;int&gt;  &lt;dbl&gt;      &lt;dbl&gt;          &lt;dbl&gt;          &lt;dbl&gt;
## 1  1.07 0.265   140 0.0224       1.98           1.02           1.11</code></pre>
<pre class="r"><code># Calculate confidence interval using bootstrap simulation
# Set seed to ensure reproducibiliity
set.seed(1)
formula_ci_bootstrap &lt;- comparison %&gt;% 
    filter(interval == &quot;2011-present&quot;) %&gt;% 
    # Specify for which variable we want to construct a C.I.
    specify(response = delta) %&gt;% 
    # Generate 1000 samples from the same data using bootstrap method (sampling with replacement)
    generate(reps = 1000, type = &quot;bootstrap&quot;) %&gt;% 
    # Calculate the mean of the 1000 bootstrapped samples
    calculate(stat = &quot;mean&quot;) %&gt;% 
    # Calculate the confidence interval based on the 1000 means from the bootstrapped samples
    get_confidence_interval(level = 0.95, type = &quot;percentile&quot;)</code></pre>
<pre><code>## Warning: Removed 4 rows containing missing values.</code></pre>
<pre class="r"><code>formula_ci_bootstrap</code></pre>
<pre><code>## # A tibble: 1 × 2
##   lower_ci upper_ci
##      &lt;dbl&gt;    &lt;dbl&gt;
## 1     1.02     1.11</code></pre>
<p><strong>What is the data showing us?</strong></p>
<p>The data is showing us that there has been a significant increase in
temperatures. We are 95% confident that the average increase in
temperatures is between 1.02 and 1.11. For the t-distribution, we took
all monthly deltas and calculated the mean and the standard deviation of
this. With that, we were able to calculate the standard error and the
t-value and estimate the confidence interval. For the bootstrapping
simulation, we generated 1000 bootstrapped samples. The code then
generated an approximate sampling distribution and calculated the
confidence interval based on that. The results suggest that we have a
global change of temperatures of more than 1 degree. If one also
consider the average annual anomaly plot (see task before), one can
clearly see that we are in a critical situation: The rise is significant
and is currently increasing dramatically.</p>
</div>
</div>
